### ISSUE TITLE
磁気センサが反応してない

### ISSUE THREAD

**Issue by wildriver** [ubi-naist/SenStick#18]
12月27日に，SenStick3とiOSアプリを繋いでみたところ，磁気センサのグラフが横棒のまま変化しない．

**Comment by reinforce-lab** [comment]
054e032 I2Cの速度は100kHzにすることで、磁気センサーが動くようになりました。

nRF52版では、I2Cの通信速度を400kHzに設定すると、磁気センサーの値が取れません。nRF51版では400kHzで動いていたのですが。
nRF52版でも100kHzにすれば、磁気センサーが動きます。センサからの情報取得としては、100kHzでよいのですが、早いに越したことはなかろうと、センサが対応する上限の400kHzに設定していました。
