### ISSUE TITLE
Androidから接続すると振る舞いがおかしくなる

### ISSUE THREAD

**Issue by reinforce-lab** [ubi-naist/SenStick#6]
Androidから接続、
1秒周期でLED点灯、
iOSアプリで接続、接続はできる、センサーデータ取得ができない、デバイス名が空欄、HW/SWバージョンは表示される
電源リセットをかけても同じ

**Comment by reinforce-lab** [comment]
ある1つのSenStickで生じた問題。その問題が生じた個体がないと振る舞い確認ができない。到着待ち。

**Comment by wildriver** [comment]
この個体、その後、ファームがアップデートできまして、正常に戻りました。なぜその現象になったのかは不明のままです。
